DROP TABLE IF EXISTS TBL_POST;

CREATE TABLE TBL_POST(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  comments VARCHAR(500) NOT NULL,
  likes INT DEFAULT 0,
  unlikes INT DEFAULT 0
);